name: Build TimerApp (Windows + Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
      - uses: actions/upload-artifact@v4
        with:
          name: TimerApp-Windows
          path: bin/Release/net8.0/win-x64/publish/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true
      - uses: actions/upload-artifact@v4
        with:
          name: TimerApp-Linux
          path: bin/Release/net8.0/linux-x64/publish/