name: Build Python TimerApp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Install PyInstaller and Qt dependencies
        run: |
          poetry add pyinstaller --group dev
          sudo apt-get update
          sudo apt-get install -y python3-pyqt5

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller --onefile --name TimerApp \
            --add-data "src/fonts:fonts" \
            --add-data "src/media:media" \
            --add-data "src/styles:styles" \
            --add-data "libs/logger/config.py:libs/logger" \
            --add-data "libs/logger/config.py:libs/logger/config.py" \
            --hidden-import PyQt5 \
            --hidden-import PyQt5.QtWidgets \
            --hidden-import PyQt5.QtCore \
            --hidden-import PyQt5.QtGui \
            src/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TimerApp-Linux
          path: dist/TimerApp